name: Test Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:stable
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
      - name: Build and run Docker Compose
        run: |
          docker ps
      
